{
 "title": "Gatling Report Trend",
 "description": "Gatling Report Trends for Grafana",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy (archive)", "query": "SHOW RETENTION POLICIES" },
   { "name": "new", "label": "Retention policy (new)", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "simulation",
    "label": "Simulation",
    "query": "SELECT DISTINCT(\"simulation\") FROM \n  (SELECT last(\"mean\") FROM \"$new\".\"gatling\" GROUP BY \"simulation\"),\n  (SELECT last(\"mean\") FROM \"$archive\".\"gatling\" GROUP BY \"simulation\")\nWHERE $timeFilter"
   },
   {
    "name": "mean_max",
    "query": "SELECT max(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"$archive\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "mean_mean",
    "query": "SELECT mean(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"$archive\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "mean_median",
    "query": "SELECT median(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"$archive\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "duration_median",
    "query": "SELECT median(\"Duration\") FROM (\nSELECT SUM(\"e\") as \"Duration\" FROM\n(SELECT elapsed(\"count\", 1s) as \"e\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"run\")\nGROUP BY  \"run\"\n)"
   },
   {
    "name": "userCount",
    "label": "Users",
    "query": "SELECT DISTINCT(\"userCount\") FROM \n  (SELECT last(\"mean\") FROM \"$new\".\"gatling\" GROUP BY \"userCount\"),\n  (SELECT last(\"mean\") FROM \"$archive\".\"gatling\" GROUP BY \"userCount\")\nWHERE $timeFilter"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "SELECT DISTINCT(\"region\") FROM \n  (SELECT last(\"mean\") FROM \"$new\".\"gatling\" GROUP BY \"region\"),\n  (SELECT last(\"mean\") FROM \"$archive\".\"gatling\" GROUP BY \"region\")\nWHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Test Details",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") AS \"OK\", mean(\"mean\") AS \"Mean\", mean(\"mean\")  / ${mean_median} AS \"Mean / median(Mean)\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok' AND \"simulation\" =~ /^$simulation$/) AND $timeFilter GROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "userCount", "operator": "=~", "value": "/^$userCount$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "userCount", "operator": "=~", "value": "/^$userCount$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "userCount", "operator": "=~", "value": "/^$userCount$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Duration\" AS \"Duration\",  \"run\"\nFROM (\nSELECT SUM(\"e\") as \"Duration\" \nFROM\n(SELECT elapsed(\"count\", 1s) as \"e\" FROM \"$archive\".\"gatling\" WHERE (\"region\" =~ /^$region$/ AND \"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND \"userCount\" =~ /^$userCount$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"run\")\nGROUP BY  \"run\"\n)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT min(\"min\") AS \"min\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok' AND \"simulation\" =~ /^$simulation$/) AND $timeFilter GROUP BY \"run\"",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min(ms)" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max(ms)" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mean(ms)" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles90" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "90th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles95" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "95th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles99" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "99th pct" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "userCount", "operator": "=~", "value": "/^$userCount$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "Mean2" ], "type": "alias" }
      ],
      [
       { "params": [ "userCount" ], "type": "field" },
       { "params": [ "Users" ], "type": "alias" }
      ],
      [
       { "params": [ "simulation" ], "type": "field" },
       { "params": [ "Simulation" ], "type": "alias" }
      ],
      [
       { "params": [ "region" ], "type": "field" },
       { "params": [ "Region" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "userCount", "operator": "=~", "value": "/^$userCount$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "Develop examples for Grafana 7.0.3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Test Mean Time",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    },
    {
     "title": "Test Mean Time + Mean analitics",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${mean_max}" ], "type": "math" },
         { "params": [ "Mean / max(Mean)" ], "type": "alias" }
        ],
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${mean_mean}" ], "type": "math" },
         { "params": [ "Mean / mean(Mean)" ], "type": "alias" }
        ],
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${mean_median}" ], "type": "math" },
         { "params": [ "Mean / median(Mean)" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    },
    {
     "title": "Test: OK, KO, Total join",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "OK" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    },
    {
     "title": "Test: %OK and %Fail ",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "OK" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    },
    {
     "title": "Test Duration",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT SUM(\"e\") as \"Duration\" FROM\n(SELECT elapsed(\"count\", 1s) as \"e\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"run\")\nGROUP BY  \"run\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         { "params": [ "1s" ], "type": "elapsed" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Test Duration with Finish Time (precise)",
     "type": "table",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 81 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT last(\"d\") AS \"Duration\"\nFROM (\n    SELECT cumulative_sum(elapsed(last(\"count\"), 1s)) AS \"d\"\n    FROM \"$archive\".\"gatling\"\n    WHERE \"simulation\" = '$simulation' AND $timeFilter\n    GROUP BY time(1s),  \"run\"\n) \nWHERE $timeFilter\nGROUP BY \"run\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "elapsed" },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Test Duration with Finish Time",
     "type": "table",
     "gridPos": { "h": 13, "w": 11, "x": 11, "y": 81 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT last(\"d\") AS \"Duration\"\nFROM (\n    SELECT cumulative_sum(elapsed(last(\"count\"), 1s)) AS \"d\"\n    FROM \"$archive\".\"gatling\"\n    WHERE \"simulation\" = '$simulation' AND $timeFilter\n    GROUP BY time(10s),  \"run\"\n) \nWHERE $timeFilter\nGROUP BY \"run\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "elapsed" },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Test Duration with Finish Time  join  Total",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 94 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT last(\"d\") AS \"Duration\"\nFROM (\n    SELECT cumulative_sum(elapsed(last(\"count\"), 1s)) AS \"d\"\n    FROM \"$archive\".\"gatling\"\n    WHERE \"simulation\" = '$simulation' AND $timeFilter\n    GROUP BY time(1s),  \"run\"\n) \nWHERE $timeFilter\nGROUP BY \"run\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "elapsed" },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "run" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Test Duration with Finish Time",
     "type": "table",
     "gridPos": { "h": 25, "w": 5, "x": 0, "y": 107 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \n    (last(\"duration\")*2+10) as \"Duration\" \nFROM\n    (SELECT \n         cumulative_sum(elapsed(last(\"count\"), 1s)) as \"duration\" \n     FROM \"$archive\".\"gatling\" \n     WHERE \n         (\"simulation\" =~ /^${simulation:regex}$/) AND \n          $timeFilter \n     GROUP BY time(1s),  \"run\"\n) \nGROUP BY \"run\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}