apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    user: admin
    password: admin
    database: gatlingdb
    url: http://influxdb:8086
    isDefault: true
    editable: true
    basicAuth: false